//
//  CTranslation.swift
//  Melia
//
//  Created by Raphaël Calabro on 30/04/2022.
//

import Foundation
import MeliceFramework

func translateToC(tree: TokenTree, for definition: MELSpriteDefinition) -> String {
    let today = Date().formatted(.dateTime.day(.twoDigits).month(.twoDigits).year(.defaultDigits))

    let sprite = MELSpriteAllocStandalone(definition)
    var finalTree = tree.reduceByInliningValues(from: sprite)

    let spriteName = definition.nameAsString.lowercased()
    var scriptName = spriteName
    if let loadScript = definition.loadScript,
       let loadScript = String(utf8String: loadScript) {
        scriptName = loadScript
    }

    var cCode = """
//
//  \(spriteName).h
//
//  Generated by Melia on \(today).
//

#ifndef \(spriteName)_h
#define \(spriteName)_h

#include "common.h"
#include "../lib/melice.h"

void \(scriptName)_update(LCDSprite * _Nonnull sprite);

#endif /* \(spriteName)_h */

"""

    cCode = cCode + """
//
//  \(spriteName).c
//
//  Generated by Melia on \(today).
//

#include "\(spriteName).h"

#include "../gen/sprite\(spriteName).h"

extern MELRectangle camera;

"""

    

    return cCode
}
